# main menu navigation url and icon
# 配置菜单导航的名称、路径和图标icon.
menu:
  Index:
    url: /
    icon: fa-home
  Tags:
    url: /tags
    icon: fa-tags
  Categories:
    url: /categories
    icon: fa-bookmark
  Archives:
    url: /archives
    icon: fa-archive
  Audio-visual:
    url: /Audio-visual
    icon: fa-music
  # List: 
  # url: /List
  # icon: fa-heartbeat
  # children: 
  #   -
  #     name: 音乐
  #     url: /List/music
  #     icon: fa-music
  #   -
  #     name: 视频
  #     url: /List/movies
  #     icon: fa-film
  About:
    url: /about
    icon: fa-user-circle-o
  Contact:
    url: /contact
    icon: fa-envelope
  Friends:
    url: /friends
    icon: fa-address-book



# Index cover carousel configuration.
# 首页封面轮播图的相关配置.
cover:
  showPrevNext: true # 是否显示左右切换按钮. Whether to display the left and right toggle buttons.
  showIndicators: true # 是否显示指示器. # Whether to display the indicators
  autoLoop: false # 是否自动轮播. Whether it is automatically rotated.
  duration: 120 # 切换延迟时间. Switching delay time.
  intervalTime: 5000 # 自动切换下一张的间隔时间. Automatically switch the interval of the next one.

# index page dream text,
# 配置首页显示"梦想"的语句.
dream:
  enable: true
  showTitle: true
  title: 我的梦想
  text: 不是每个人都应该像我这样去建造一座水晶大教堂，但是每个人都应该拥有自己的梦想，设计自己的梦想，追求自己的梦想，实现自己的梦想。梦想是生命的灵魂，是心灵的灯塔，是引导人走向成功的信仰。有了崇高的梦想，只要矢志不渝地追求，梦想就会成为现实，奋斗就会变成壮举，生命就会创造奇迹。——罗伯·舒乐

# Whether to display the musics.
# 是否在首页显示音乐.
music:
  enable: true
  showTitle: false
  title: 听听音乐
  fixed: false # 开启吸底模式
  autoplay: false # 是否自动播放
  theme: '#542674'
  loop: 'all' # 音频循环播放, 可选值: 'all', 'one', 'none'
  order: 'list' # 音频循环顺序, 可选值: 'list', 'random'
  preload: 'auto' # 预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.7 # 默认音量，请注意播放器会记忆用户设置，用户手动设置音量后默认音量即失效
  listFolded: false # 列表默认折叠
  listMaxHeight: "197px" #列表最大高度

# Whether to display the videos.
# 是否在首页显示视频.
video:
  enable: true
  showTitle: true
  title: 看看视频
  url: https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4 # 必填
  pic:
  thumbnails:
  height: # 如：400
  autoplay: false # 是否自动播放
  theme: '#42b983'
  loop: true # 是否循环播放
  preload: 'auto' # 预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.7


# Whether to display the title of the recommended posts
# 是否显示推荐文章的标题
recommend:
  showTitle: true

# Configure website favicon and LOGO
# 配置网站favicon和网站LOGO
favicon: https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/favicon.png
logo: https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/logo.png

# The configuration of the second button in the home banner,
# including the display name of the button, the font awesome icon, and the hyperlink to the button.
# 首页 banner 中的第二个按钮的配置，包括按钮的显示名称、font awesome图标和按钮的超链接.
indexbtn:
  enable: true
  name: Github
  icon: fa-github-alt
  url: https://github.com/spade-z-1/

# The configurations of the second line of home banner
# icon/button will not show up if you leave the corresponding socialLink empty
# 首页 banner 中的第二行个人信息配置，留空即不启用
socialLink:
  qq: 2859683701
  github: SpadeZ-A
  weibo: 
  email: plasticpheasant4587@gmail.com
  zhihu: spade-z-48 

# Whether to activate the Post TOC, and Configure which title types are supported by TOC support.
# You can add `toc: false` to the Front-matter of a post to turn off the TOC.
# 是否激活文章 TOC 功能，并配置TOC支持选中哪些标题类型，这是全局配置。
# 可以在某篇文章的 Front-matter 中再加上`toc: false`，使该篇文章关闭TOC目录功能
toc:
  enable: true
  heading: h1, h2, h3, h4, h5
  showToggleBtn: true # 是否显示切换TOC目录展开收缩的按钮

# Whether the code is broken.
# 代码是否换行
code:
  break: false

# 是否激活文章末尾的打赏功能，默认激活（你替换为的你自己的微信、支付宝二维码图片、或者使用网络图片也可以）.
reward:
  enable: true
  title: 你的赏识是我前进的动力!
  wechat: https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/wechat.bmp
  alipay: https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/alipay.bmp

# Whether to activate the copyright information of the blog and author when copying the post content.
# minCharNumber: Approve copyright information by copying at least how many characters.
# 是否激活复制文章时追加博客和作者的版权信息.
copyright:
  enable: true
  minCharNumber: 120 # 至少复制多少个字符就追加版权信息.
  description: 本文章著作权归作者所有，任何形式的转载都请注明出处。

# Whether to activate the mathjax, this is a global configuration, but the post still does not open the mathjax rendering.
# Considering that the mathjax loading is time consuming,
# you also need to add `mathjax: true` to the Front-matter of the post that needs to be rendered.
# 是否激活mathjax数学公式，这是全局配置，但文章仍然不会都开启mathjax渲染，
# 考虑到mathjax加载比较耗时，你还需要在需要渲染的文章的Front-matter中再加上`mathjax: true`才行.
mathjax:
  enable: true
  cdn: https://cdn.bootcss.com/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Post word count, reading duration, site total word count.
# Before you activate, please confirm that you have installed the hexo-wordcount plugin,
# install the plugin command: `npm i --save hexo-wordcount`.
# 文章字数统计、阅读时长、总字数统计
# 激活前请确认你已经安装了 hexo-wordcount 插件，安装命令: `npm i --save hexo-wordcount`
wordCount:
  enable: true
  postWordCount: true
  min2read: true
  totalCount: true

# Whether to activate the 'love' effect of clicking on the page.
# 是否激活点击页面的'爱心'效果，默认激活.
clicklove:
  enable: true

# profile in about page, including avatars, career, and personal introductions.
# 在”关于”页面中配置个人信息，包括头像、职业和个人介绍.
profile:
  avatar: https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/SpadeZ.jpg
  career: 辽宁科技大学 | 计算机与软件工程学院 | 计算机科学与技术
  introduction: 

# config my projects informations in about page.
# If you don't want to display this `My Projects` content, you can deactivate or delete this configuration.
# 在“关于”页面配置"我的项目"信息，如果你不需要这些信息则可以将其设置为不激活或者将其删除.
myProjects:
  enable: false
  data:
    DeepLearning-500-questions:
      icon: fa-file-text-o
      iconBackground: 'linear-gradient(to bottom right, #29B6F6 0%, #1E88E5 100%)'
      url: https://github.com/scutan90/DeepLearning-500-questions
      desc: 深度学习500问，以问答形式对常用的概率知识、线性代数、机器学习、深度学习、计算机视觉等热点问题进行阐述，以帮助自己及有需要的读者。 全书分为18个章节，50余万字。.
    hexo-theme-matery:
      icon: fa-meetup
      iconBackground: 'linear-gradient(to bottom right, #66BB6A 0%, #81C784 100%)'
      url: http://github.com/blinkfox/hexo-theme-matery
      desc: This is a Hexo blog theme with 'Material Design' and responsive design.
    hexo-blog-fly:
      icon: fa-file-text-o
      iconBackground: 'linear-gradient(to bottom right, #29B6F6 0%, #1E88E5 100%)'
      url: https://github.com/shw2018/hexo-blog-fly
      desc: 我的博客源码开源小项目


# config my skills informations in about page.
# If you don't want to display this `My Skills` content, you can deactivate or delete this configuration.
# 在“关于”页面配置"我的技能"信息，如果你不需要这些信息则可以将其设置为不激活或者将其删除.
mySkills:
  enable: true
  data:
    算法:
      background: 'linear-gradient(to right, #FF0066 0%, #FF00CC 100%)'
      percent: 60%
    C++:
      background: 'linear-gradient(to right, #9900FF 0%, #CC66FF 100%)'
      percent: 80%
    Python:
      background: 'linear-gradient(to right, #2196F3 0%, #42A5F5 100%)'
      percent: 5%
    Java:
      background: 'linear-gradient(to right, #00BCD4 0%, #80DEEA 100%)'
      percent: 60%
    SQL:
      background: 'linear-gradient(to right, #4CAF50 0%, #81C784 100%)'
      percent: 50%
    HTML:
      background: 'linear-gradient(to right, #FFEB3B 0%, #FFF176 100%)'
      percent: 50%

# Whether to display post-calender in the `archive` page
# 设置在归档页面中是否显示'文章日历'控件
postCalendar: true

# the Gitalk config，default disabled
# Gitalk 评论模块的配置，默认为不激活
gitalk:
  enable: true
  owner: spade-z-1
  repo: Blog-comment
  oauth:
    clientId: 2d725af13c37ac1fd6d0
    clientSecret: d890a49875a50a2ecbe652eeb96bb982373020e3
  admin:
    - spade-z-1

# the Gitment config，default disabled
# Gitment 评论模块的配置，默认为不激活
gitment:
  enable: false
  owner: Spade-Z
  repo:
  oauth:
    clientId: 
    clientSecret: 

# disqus config, default disabled
# Disqus评论模块的配置，默认为不激活
disqus:
  enable: false
  shortname:

# Livere comment configuration, the default is not activated
# Livere 来必力评论模块的配置，默认为不激活
livere:
  enable: false
  uid:

# The configuration of the Valine comment module is not activated by default.
# To use it, activate the configuration item and set appId and appKey.
# Valine 评论模块的配置，默认为不激活，如要使用，就请激活该配置项，并设置 appId 和 appKey.
valine:
  enable: true
  appId: BppJAl9iCAm1fI1nvBYBNAau-MdYXbMMI
  appKey: l3mOLJVxyVA6wtvMoGaGOM30
  notify: true
  verify: true
  visitor: true
  #avatar: 'mm' # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
  avatar: https://www.gravatar.com/userimage/182354812/737942809629557f36c8c78187a82afc?size=120
  pageSize: 10
  placeholder: 'just go go' # Comment Box placeholder

# Whether to display fork me on github icon and link, default true, You can change it to your repo address
# 配置是否在 header 中显示 fork me on github 的图标，默认为true，你可以修改为你的仓库地址.
githubLink:
  enable: true
  url: https://github.com/SpadeZ-A/SpadeZ-A.github.io
  title: Fork Me

# The password verification feature of read post. To use this feature,
# activate the configuration item and write the 'password' key and Cipher in the post's Front-matter.
# Note: In order to ensure that the original password will not be leaked to the web page,
# the password of the article must be encrypted by 'SHA256' so that it will not be cracked.
# 阅读文章的密码验证功能，如要使用此功能请激活该配置项，并在对应文章的Front-matter中写上'password'的键和加密后的密文即可.
# 请注意：为了保证密码原文不会被泄露到网页中，文章的密码必须是通过'SHA256'加密的，这样就不会被破解.
verifyPassword:
  enable: true
  promptMessage: 请输入访问本文章的密码
  errorMessage: 密码错误，将返回主页！

# busuanzi(http://busuanzi.ibruce.info/) website statistics
# 不蒜子(http://busuanzi.ibruce.info/) 网站统计
busuanziStatistics:
  enable: true
  totalTraffic: true # 总访问量
  totalNumberOfvisitors: true # 总人次

# Add google analytics configuration
# 添加 Google Analytics 配置
googleAnalytics:
  enable: false
  id: UA-144253917-1

# The used front-end library can be replaced with the corresponding CDN address as needed,
# If the specific version is not specified below, you can use the latest version.
# 使用到的前端库，可按需替换成对应的CDN地址，如果下面未指定具体的版本号，使用最新的版本即可.
libs:
  css:
    fontAwesome: /libs/awesome/css/font-awesome.min.css # V4.7.0
    materialize: /libs/materialize/materialize.min.css # 1.0.0
    aos: /libs/aos/aos.css
    animate: /libs/animate/animate.min.css # V3.5.1
    lightgallery: /libs/lightGallery/css/lightgallery.min.css # V1.6.11
    aplayer: /libs/aplayer/APlayer.min.css
    dplayer: /libs/dplayer/DPlayer.min.css
    gitalk: /libs/gitalk/gitalk.css
    jqcloud: /libs/jqcloud/jqcloud.css
    tocbot: /libs/tocbot/tocbot.css
    fancybox: https://cdn.staticfile.org/fancybox/3.5.7/jquery.fancybox.min.css
    justifiedGallery: https://cdn.staticfile.org/justifiedGallery/3.7.0/css/justifiedGallery.min.css
    share: /libs/share/css/share.min.css
    my: /css/my.css
    matery: /css/matery.css
  js:
    jquery: /libs/jquery/jquery-2.2.0.min.js
    materialize: /libs/materialize/materialize.min.js # 1.0.0
    masonry: /libs/masonry/masonry.pkgd.min.js # v4.0.0
    aos: /libs/aos/aos.js
    scrollProgress: /libs/scrollprogress/scrollProgress.min.js
    lightgallery: /libs/lightGallery/js/lightgallery-all.min.js # V1.6.11
    clicklove: /libs/others/clicklove.js
    busuanzi: /libs/others/busuanzi.pure.mini.js
    aplayer: /libs/aplayer/APlayer.min.js
    dplayer: /libs/dplayer/DPlayer.min.js
    crypto: /libs/cryptojs/crypto-js.min.js
    echarts: /libs/echarts/echarts.min.js
    gitalk: /libs/gitalk/gitalk.min.js
    jqcloud: /libs/jqcloud/jqcloud-1.0.4.min.js
    tocbot: /libs/tocbot/tocbot.min.js
    fancybox: https://cdn.staticfile.org/fancybox/3.5.7/jquery.fancybox.min.js
    justifiedGallery: https://cdn.staticfile.org/justifiedGallery/3.7.0/js/jquery.justifiedGallery.min.js
    lazyload: /libs/lazyload/jquery.lazyload.js
    share: /libs/share/js/social-share.min.js
    matery: /js/matery.js
    search: /js/search.js
    sakura: /js/sakura.js
    fireworks: /js/fireworks.js
    wenzi: /js/wenzi.js
    xuehuapiaoluo: /js/xuehuapiaoluo.js
    instant.page: /js/instant.page.js
    canvas_nest: /libs/background/canvas-nest.js
    ribbon: /libs/background/ribbon.min.js
    ribbon_dynamic: /libs/background/ribbon-dynamic.js

# The post featured images that needs to be displayed when there is no image.
# 无文章特色图片时需要显示的文章特色图片.
featureImages: 
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages0.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages1.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages2.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages3.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages4.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages5.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages6.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages7.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages8.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages9.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages10.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages11.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages12.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages13.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages14.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages15.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages16.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages17.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages18.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages19.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages20.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages21.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages22.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages23.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages24.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages25.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages26.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages27.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages28.jpg
- https://cdn.jsdelivr.net/gh//SpadeZ-A/cdn/img/featureimages29.jpg

  # default configs that the default policy for every articles/posts
  # default 配置文章的默认转载规则

  # you can define reprint policy for a single article in the front-matter of the specific md file using this key: reprintPolicy
  # 您可以使用在文章md文件的 front-matter 中指定 reprintPolicy 来给单个文章配置转载规则

  # 可用的转载规则有（available reprint policies are）：
  # 这些转载规则的意义请参考(you can refer to this link FMI)：https://creativecommons.org/choose/?lang=zh
  # cc_by（知识共享署名 4.0 国际许可协议 Creative Commons Attribution-NoDerivatives 4.0 International License）
  # cc_by_nd（知识共享署名-禁止演绎 4.0 国际许可协议 Creative Commons Attribution-NoDerivatives 4.0 International License）
  # cc_by_sa（知识共享署名-相同方式共享 4.0 国际许可协议 Creative Commons Attribution-ShareAlike 4.0 International License）
  # cc_by_nc（知识共享署名-非商业性使用 4.0 国际许可协议 Creative Commons Attribution-NoDerivatives 4.0 International License）
  # cc_by_nc_nd（知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议 Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License）
  # cc_by_nc_sa（知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议 Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License）

  # cc0（CC0 1.0 通用 (CC0 1.0) 公共领域贡献 CC0 1.0 Universal (CC0 1.0) Public Domain Dedication） https://creativecommons.org/publicdomain/zero/1.0/deed.zh

  # noreprint（不允许转载 not allowed to reprint）
  # pay（付费转载 pay for reprinting）

reprint:
  enable: fasle # whether enable reprint section 是否启用“转载规则限定模块”
  default: cc_by

# Enable baidu push so that the blog will push the url to baidu automatically which is very helpful for SEO
baidu_push: true

# 页面樱花飘落动效
sakura:
  enable: true

# 鼠标点击烟花爆炸动效
fireworks:
  enable: true

# 天气控件 Weather Widget
weather:
  enable: true

# 鼠标点击文字特效 
wenzi:
  enable: true

# 背景雪花飘落特效
xuehuapiaoluo:
  enable: false0000

# banner 是否每日切换.
# 若为 false, 则 banner 默认为 banner0.jpg
banner:
  enable: false

# Tidio online contact 
tidio:
  enable: true
  public_key: xxxxxxxxxxxxxxxxxxxxxxxxxxx

#背景canvas-nest
canvas_nest:
  enable: true
  color: 0,0,255 #线条颜色, 默认: '0,0,0' ；三个数字分别为(R,G,B)，注意用,分割
  pointColor: 0,0,255 #交点颜色, 默认: '0,0,0' ；三个数字分别为(R,G,B)，注意用,分割
  opacity: 0.8 # 线条透明度（0~1）, 默认: 0.5
  zIndex: -1 # 背景的z-index属性，css属性用于控制所在层的位置, 默认: -1
  count: 150 # 线条的总数量, 默认: 99

#背景静止彩带
ribbon:
  enable: false
  size: 150 #彩带大小, 默认: 90
  alpha: 0.6 #彩带透明度 (0 ~ 1), 默认: 0.6
  zIndex: -1 #背景的z-index属性，css属性用于控制所在层的位置, 默认: -1
  click_to_change: false  #设置是否每次点击都更换彩带

#背景动态彩带
ribbon_dynamic:
  enable: true 

# CDN访问加速 
# 第一次使用本功能，一定要先配置url，再`hexo cl && hexo g && hexo d`部署到GitHub的仓库，注意！必须是GitHub的仓库！
# 如果必须要使用国内的coding或者gitee，可以采用双部署，同时将网站部署到两个仓库（其中一个必须是GitHub的仓库）
# URL配置规则（例子如下）： https://cdn.jsdelivr.net/gh/你的GitHub用户名/你的仓库名
# 如果想关闭此功能，将 url地址 注释或删除即可！
#
# 注：配置了此项，就代表着本地调试的时候，网站依然会去GitHub请求资源（原来的资源），本地调试的时候记得将 此项配置 注释或者删除掉
# 更多关于访问速度优化，请查看：https://blog.sky03.cn/posts/42790.html
jsDelivr:
  url: # https://cdn.jsdelivr.net/SpadeZ-A/cdn.git




